"""Update db

Revision ID: 2988aea29e5e
Revises: 
Create Date: 2022-05-09 15:16:10.662719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2988aea29e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitch_timestamp'), 'pitch', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitch_timestamp'), table_name='pitch')
    op.drop_table('pitch')
    # ### end Alembic commands ###
