"""add pitch title

Revision ID: 734e11f0e889
Revises: aacc21e96679
Create Date: 2022-05-11 12:27:13.250606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734e11f0e889'
down_revision = 'aacc21e96679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
