"""Add vote table

Revision ID: bacdcb1126bd
Revises: d63b9cf327af
Create Date: 2022-05-12 12:32:29.924684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacdcb1126bd'
down_revision = 'd63b9cf327af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('votes_user_id_fkey', 'votes', type_='foreignkey')
    op.drop_column('votes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('votes_user_id_fkey', 'votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
